version: '3.8'

services:
  ee.mongo:
    image: mongo:4.2
    container_name: ee.mongo
    ports:
      - "27777:27017"
    expose:
      - 27777
    networks:
      - ee_net
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - mongodb-data:/data/db

volumes:
  mongodb-data:

networks:
  ee_net:
    external: true